#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    register-with-eureka: false
#    fetch-registry: true
#    service-url:
#      defaultZone: http://devsalesp.sunlands.wang:8761/eureka/

spring:
  datasource:
    url: jdbc:p6spy:mysql://bj-cdb-fmhcv6zw.sql.tencentcdb.com:62785/salesplatform_sales_dev?useSSL=false&characterEncoding=utf8&autoReconnect=true
    username: salesp_sales_dev
    password: xd7RufAmwQIahgQ5
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    tomcat:
      initial-size: 2
      max-active: 2
      min-idle: 2
      max-idle: 2
      test-on-borrow: true
  rabbitmq:
    addresses: 62.234.206.233
    port: 5672
    username: sunlands2018
    password: Shangde2018
  redis:
    host: 62.234.206.233
    port: 16379
    password: SunLands2018
    database: 15
    timeout: 10000
    pool:
      max-active: 200
      max-wait: -1
      max-idle: 200
      min-idle: 200

security:
  oauth2:
    client:
      client-id: web-api
      client-secret: 123456
      access-token-uri: https://devsalesp.sunlands.wang/salesplatform-web-api/oauth/check_token

netty:
  server:
    backlog: 5000
    port: 8090
    parentgroup:
      size: 2
    childgroup:
      size: 4

#定义接入方, 包括http端(user)和websocket端(sales) @see ClientInfo
clients:
- clientId: mp
  userIdentity: user
  callbackProtocol: http
  callbackUrl: https://testmp.sunlands.wang/mp-message-service/inner/sales/message
  resourcePackageCallbackUrl: https://testmp.sunlands.wang/mp-message-service/resourceCard/sendResourceMsg
- clientId: mp
  userIdentity: sale
  callbackProtocol: websocket
  callbackUrl: localhost

logging:
  level:
    com:
      sunlands: debug
